### ISSUE TITLE
There is no AMIID for ap-northeast-2

### ISSUE THREAD

**Issue by imjanghyuk** [awslabs/amazon-ecs-nodejs-microservices#9]
I can't make CloudFormation stack.
When I click create button, 'Template validation error: Template error: Unable to get mapping for AWSRegionToAMI::ap-northeast-2::AMIID' error throws.

**Comment by afrobambacar** [comment]
I faced exactly same problem. so I added AMIID for ap-northeast-2 into the `esc.yml` and I used it. The ECS-Optimized AMIID list is in [this doc](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html)

Just add this line to `esc.yml` files.
```
Mappings:
  AWSRegionToAMI:
    ap-northeast-2:
      AMIID: ami-0060ad36f655af38b
    ...
```
